### ISSUE TITLE
Template variables in options.vars

### ISSUE THREAD

**Issue by vnenkpet** [luskhq/launchkit#3]
Wondering if it wouldn't be a good idea to make this:

`const aliasURL = mustache.render(options.alias, process.env);`

work for the options.vars as well and not only alias, so it's possible to do something like:

```
default:
    options:
        vars:
            EMAIL_PREFIX: '{{CIRCLE_BRANCH}}'
```
